# Generated by Django 2.1.2 on 2019-02-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190131_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_courses', models.CharField(max_length=50)),
                ('teacher_course_date', models.DateTimeField(verbose_name='date starting')),
            ],
        ),
    ]
